### ISSUE TITLE
Unable to build on macOS High Sierra

### ISSUE THREAD

**Issue by arsal-wal** [rgeo/rgeo#180]
Xcode Version 9.2 (9C40b)

**Output of `gcc -v`**

```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Output of `brew info geos`**

```
geos: stable 3.6.2 (bottled)
Geometry Engine
https://trac.osgeo.org/geos
/usr/local/Cellar/geos/3.6.2 (402 files, 8.7MB) *
  Poured from bottle on 2017-12-14 at 10:55:36
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/geos.rb
==> Dependencies
Build: swig ✘
==> Options
--with-ruby
	Build the ruby extension
--without-python
	Do not build the Python extension
==> Caveats
Python modules have been installed and Homebrew's site-packages is not
in your Python sys.path, so you will not be able to import the modules
this formula installed. If you plan to develop with these modules,
please run:
  mkdir -p /Users/arsal/Library/Python/2.7/lib/python/site-packages
  echo 'import site; site.addsitedir("/usr/local/lib/python2.7/site-packages")' >> /Users/arsal/Library/Python/2.7/lib/python/site-packages/homebrew.pth
```

**Output of `gem install rgeo`**

```
Building native extensions.  This could take a while...
ERROR:  Error installing rgeo:
	ERROR: Failed to build gem native extension.

    current directory: /Users/arsal/.rvm/gems/ruby-2.4.2@lmcom/gems/rgeo-1.0.0/ext/geos_c_impl
/Users/arsal/.rvm/rubies/ruby-2.4.2/bin/ruby -r ./siteconf20180126-50790-13d2rsi.rb extconf.rb
checking for geos-config... yes

checking for geos_c.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/arsal/.rvm/rubies/ruby-2.4.2/bin/$(RUBY_BASE_NAME)
	--with-geos-config
	--without-geos-config
/Users/arsal/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/mkmf.rb:457:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /Users/arsal/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/mkmf.rb:588:in `try_cpp'
	from /Users/arsal/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/mkmf.rb:1095:in `block in have_header'
	from /Users/arsal/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/mkmf.rb:945:in `block in checking_for'
	from /Users/arsal/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/mkmf.rb:351:in `block (2 levels) in postpone'
	from /Users/arsal/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/mkmf.rb:321:in `open'
	from /Users/arsal/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/mkmf.rb:351:in `block in postpone'
	from /Users/arsal/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/mkmf.rb:321:in `open'
	from /Users/arsal/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/mkmf.rb:347:in `postpone'
	from /Users/arsal/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/mkmf.rb:944:in `checking_for'
	from /Users/arsal/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/mkmf.rb:1094:in `have_header'
	from extconf.rb:27:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Users/arsal/.rvm/gems/ruby-2.4.2@lmcom/extensions/x86_64-darwin-17/2.4.0/rgeo-1.0.0/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Users/arsal/.rvm/gems/ruby-2.4.2@lmcom/gems/rgeo-1.0.0 for inspection.
Results logged to /Users/arsal/.rvm/gems/ruby-2.4.2@lmcom/extensions/x86_64-darwin-17/2.4.0/rgeo-1.0.0/gem_make.out
```

**Output of `cat /Users/arsal/.rvm/gems/ruby-2.4.2@lmcom/extensions/x86_64-darwin-17/2.4.0/rgeo-1.0.0/mkmf.log`**

```
find_executable: checking for geos-config... -------------------- yes

--------------------

"gcc -o conftest -I/Users/arsal/.rvm/rubies/ruby-2.4.2/include/ruby-2.4.0/x86_64-darwin17 -I/Users/arsal/.rvm/rubies/ruby-2.4.2/include/ruby-2.4.0/ruby/backward -I/Users/arsal/.rvm/rubies/ruby-2.4.2/include/ruby-2.4.0 -I. -I/usr/local/Cellar/geos/3.6.2/include  -I/usr/local/opt/libyaml/include -I/usr/local/opt/readline/include -I/usr/local/opt/libksba/include -I/usr/local/opt/openssl@1.1/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   -O3 -fno-fast-math -ggdb3 -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wno-tautological-compare -Wno-parentheses-equality -Wno-constant-logical-operand -Wno-self-assign -Wunused-variable -Wimplicit-int -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wshorten-64-to-32 -Wimplicit-function-declaration -Wdivision-by-zero -Wdeprecated-declarations -Wextra-tokens  -fno-common -pipe conftest.c  -L. -L/Users/arsal/.rvm/rubies/ruby-2.4.2/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/libksba/lib -L/usr/local/opt/openssl@1.1/lib -L. -fstack-protector -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/libksba/lib -L/usr/local/opt/openssl@1.1/lib     -L/usr/local/Cellar/geos/3.6.2/lib -lgeos_c -lruby.2.4.2  -lpthread -lgmp -ldl -lobjc "
In file included from conftest.c:1:
In file included from /Users/arsal/.rvm/rubies/ruby-2.4.2/include/ruby-2.4.0/ruby.h:33:
In file included from /Users/arsal/.rvm/rubies/ruby-2.4.2/include/ruby-2.4.0/ruby/ruby.h:36:
In file included from /Users/arsal/.rvm/rubies/ruby-2.4.2/include/ruby-2.4.0/ruby/defines.h:101:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk/usr/include/stdio.h:64:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk/usr/include/sys/cdefs.h:761:2: error: Unsupported architecture
#error Unsupported architecture
 ^
In file included from conftest.c:1:
In file included from /Users/arsal/.rvm/rubies/ruby-2.4.2/include/ruby-2.4.0/ruby.h:33:
In file included from /Users/arsal/.rvm/rubies/ruby-2.4.2/include/ruby-2.4.0/ruby/ruby.h:36:
In file included from /Users/arsal/.rvm/rubies/ruby-2.4.2/include/ruby-2.4.0/ruby/defines.h:101:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk/usr/include/stdio.h:67:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk/usr/include/_types.h:27:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk/usr/include/sys/_types.h:33:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk/usr/include/machine/_types.h:34:2: error: architecture not supported
#error architecture not supported
 ^
In file included from conftest.c:1:
In file included from /Users/arsal/.rvm/rubies/ruby-2.4.2/include/ruby-2.4.0/ruby.h:33:
In file included from /Users/arsal/.rvm/rubies/ruby-2.4.2/include/ruby-2.4.0/ruby/ruby.h:36:
In file included from /Users/arsal/.rvm/rubies/ruby-2.4.2/include/ruby-2.4.0/ruby/defines.h:101:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk/usr/include/stdio.h:67:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk/usr/include/_types.h:27:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk/usr/include/sys/_types.h:55:9: error: unknown type name '__int64_t'; did you mean '__int128_t'?
typedef __int64_t       __darwin_blkcnt_t;      /* total blocks */
        ^
note: '__int128_t' declared here
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk/usr/include/sys/_types.h:56:9: error: unknown type name '__int32_t'; did you mean '__int128_t'?
typedef __int32_t       __darwin_blksize_t;     /* preferred block size */
        ^
note: '__int128_t' declared here
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk/usr/include/sys/_types.h:57:9: error: unknown type name '__int32_t'; did you mean '__int128_t'?
typedef __int32_t       __darwin_dev_t;         /* dev_t */
        ^
note: '__int128_t' declared here
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk/usr/include/sys/_types.h:60:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?
typedef __uint32_t      __darwin_gid_t;         /* [???] process and group IDs */
        ^
note: '__uint128_t' declared here
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk/usr/include/sys/_types.h:61:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?
typedef __uint32_t      __darwin_id_t;          /* [XSI] pid_t, uid_t, or gid_t*/
        ^
note: '__uint128_t' declared here
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk/usr/include/sys/_types.h:62:9: error: unknown type name '__uint64_t'; did you mean '__uint128_t'?
typedef __uint64_t      __darwin_ino64_t;       /* [???] Used for 64 bit inodes */
        ^
note: '__uint128_t' declared here
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk/usr/include/sys/_types.h:68:9: error: unknown type name '__darwin_natural_t'
typedef __darwin_natural_t __darwin_mach_port_name_t; /* Used by mach */
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk/usr/include/sys/_types.h:70:9: error: unknown type name '__uint16_t'; did you mean '__uint128_t'?
typedef __uint16_t      __darwin_mode_t;        /* [???] Some file attributes */
        ^
note: '__uint128_t' declared here
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk/usr/include/sys/_types.h:71:9: error: unknown type name '__int64_t'; did you mean '__int128_t'?
typedef __int64_t       __darwin_off_t;         /* [???] Used for file sizes */
        ^
note: '__int128_t' declared here
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk/usr/include/sys/_types.h:72:9: error: unknown type name '__int32_t'; did you mean '__int128_t'?
typedef __int32_t       __darwin_pid_t;         /* [???] process and group IDs */
        ^
note: '__int128_t' declared here
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk/usr/include/sys/_types.h:73:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?
typedef __uint32_t      __darwin_sigset_t;      /* [???] signal set */
        ^
note: '__uint128_t' declared here
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk/usr/include/sys/_types.h:74:9: error: unknown type name '__int32_t'; did you mean '__int128_t'?
typedef __int32_t       __darwin_suseconds_t;   /* [???] microseconds */
        ^
note: '__int128_t' declared here
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk/usr/include/sys/_types.h:75:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?
typedef __uint32_t      __darwin_uid_t;         /* [???] user IDs */
        ^
note: '__uint128_t' declared here
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk/usr/include/sys/_types.h:76:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?
typedef __uint32_t      __darwin_useconds_t;    /* [???] microseconds */
        ^
note: '__uint128_t' declared here
In file included from conftest.c:1:
In file included from /Users/arsal/.rvm/rubies/ruby-2.4.2/include/ruby-2.4.0/ruby.h:33:
In file included from /Users/arsal/.rvm/rubies/ruby-2.4.2/include/ruby-2.4.0/ruby/ruby.h:36:
In file included from /Users/arsal/.rvm/rubies/ruby-2.4.2/include/ruby-2.4.0/ruby/defines.h:101:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk/usr/include/stdio.h:67:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk/usr/include/_types.h:43:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?
typedef __uint32_t      __darwin_wctype_t;
        ^
note: '__uint128_t' declared here
In file included from conftest.c:1:
In file included from /Users/arsal/.rvm/rubies/ruby-2.4.2/include/ruby-2.4.0/ruby.h:33:
In file included from /Users/arsal/.rvm/rubies/ruby-2.4.2/include/ruby-2.4.0/ruby/ruby.h:36:
In file included from /Users/arsal/.rvm/rubies/ruby-2.4.2/include/ruby-2.4.0/ruby/defines.h:101:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk/usr/include/stdio.h:71:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk/usr/include/sys/_types/_va_list.h:31:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk/usr/include/machine/types.h:37:2: error: architecture not supported
#error architecture not supported
 ^
In file included from conftest.c:1:
In file included from /Users/arsal/.rvm/rubies/ruby-2.4.2/include/ruby-2.4.0/ruby.h:33:
In file included from /Users/arsal/.rvm/rubies/ruby-2.4.2/include/ruby-2.4.0/ruby/ruby.h:36:
In file included from /Users/arsal/.rvm/rubies/ruby-2.4.2/include/ruby-2.4.0/ruby/defines.h:101:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk/usr/include/stdio.h:71:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk/usr/include/sys/_types/_va_list.h:32:9: error: unknown type name '__darwin_va_list'
typedef __darwin_va_list va_list;
        ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */
```

**Comment by egorf** [comment]
@arsal-wal Have you been able to resolve this?
