### ISSUE TITLE
Frozen string when force_encoding in ffi_feature_methods

### ISSUE THREAD

**Issue by ldonnet** [rgeo/rgeo#211]
When we call as_text method for RGeo::Geos::FFIFactory, an error raise about Frozen string.
That happen when we read geometry from database or create point in console. 
The problem seems too big that no one else find it, so I describe the way to reproduce it. 

### Steps to reproduce

```sh
2.6.1 :013 >   WGS84_PROJ4 = '+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs'
 => "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs" 
2.6.1 :014 > 
2.6.1 :015 > f = RGeo::Geos::FFIFactory.new(
2.6.1 :016 >           srid: 4326,
2.6.1 :017 >           proj4: WGS84_PROJ4,
2.6.1 :018 >           :wkt_parser => {:support_ewkt => true, :default_srid => 4326},
2.6.1 :019 >           :wkt_generator => {:type_format => :ewkt, :emit_ewkt_srid => true},
2.6.1 :020 >           :wkb_parser => {:support_ewkb => true, :default_srid => 4326},
2.6.1 :021 >           :wkb_generator => {:type_format => :ewkb, :emit_ewkb_srid => true}
2.6.1 :022?>       )
 => #<RGeo::Geos::FFIFactory:0x2b29f4103f58 srid=4326> 
2.6.1 :023 > f.point(2,3)aceback (most recent call last):
       16: from /home/luc/.rvm/gems/ruby-2.6.1/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:259:in `load_dependency'
       15: from /home/luc/.rvm/gems/ruby-2.6.1/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:287:in `block in load'
       14: from /home/luc/.rvm/gems/ruby-2.6.1/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:287:in `load'
       13: from /home/luc/projects/referentials/bin/rails:9:in `<top (required)>'
       12: from /home/luc/.rvm/gems/ruby-2.6.1/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:293:in `require'
       11: from /home/luc/.rvm/gems/ruby-2.6.1/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:259:in `load_dependency'
       10: from /home/luc/.rvm/gems/ruby-2.6.1/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:293:in `block in require'
        9: from /home/luc/.rvm/gems/ruby-2.6.1/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:293:in `require'
        8: from /home/luc/.rvm/gems/ruby-2.6.1/gems/railties-5.0.7.2/lib/rails/commands.rb:18:in `<top (required)>'
        7: from /home/luc/.rvm/gems/ruby-2.6.1/gems/railties-5.0.7.2/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
        6: from /home/luc/.rvm/gems/ruby-2.6.1/gems/railties-5.0.7.2/lib/rails/commands/commands_tasks.rb:78:in `console'
        5: from /home/luc/.rvm/gems/ruby-2.6.1/gems/railties-5.0.7.2/lib/rails/commands/console_helper.rb:9:in `start'
        4: from /home/luc/.rvm/gems/ruby-2.6.1/gems/railties-5.0.7.2/lib/rails/commands/console.rb:65:in `start'
        3: from /home/luc/.rvm/gems/ruby-2.6.1/gems/rgeo-2.0.1/lib/rgeo/geos/ffi_feature_methods.rb:23:in `inspect'
        2: from /home/luc/.rvm/gems/ruby-2.6.1/gems/rgeo-2.0.1/lib/rgeo/geos/ffi_feature_methods.rb:107:in `as_text'
        1: from /home/luc/.rvm/gems/ruby-2.6.1/gems/rgeo-2.0.1/lib/rgeo/geos/ffi_feature_methods.rb:107:in `force_encoding'
```

### System configuration

**Ruby version**: 2.6.1

**OS**: Debian sid

**Comment by BuonOmo** [comment]
I think this issue is outdated now:

```ruby
WGS84_PROJ4 = '+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs'
f = RGeo::Geos::FFIFactory.new(
    srid: 4326,
    proj4: WGS84_PROJ4,
    :wkt_parser => {:support_ewkt => true, :default_srid => 4326},
    :wkt_generator => {:type_format => :ewkt, :emit_ewkt_srid => true},
    :wkb_parser => {:support_ewkb => true, :default_srid => 4326},
    :wkb_generator => {:type_format => :ewkb, :emit_ewkb_srid => true}
)
f.point(2,3)
```

Works for me. Feel free to open a new issue if you manage to reproduce again
