### ISSUE TITLE
rgeo 3 geom freeze behaviour

### ISSUE THREAD

**Issue by Quiwin** [rgeo/rgeo#308]
Hello,

Thanks for the work on rgeo 3 :)

I am trying to integrate it in our codebase, but I face an issue on one of our usecase.
When initiliazing our ruby stack, we instantiate and freeze some polygons to reuse them between process, this is not possible anymore on rgeo 3 because of the new validity check which update the object.

Is it a conscious choice, or a regression ?

Thanks !

### Steps to reproduce
Create a polygon, freeze it, and call #contains?
```ruby
factory = RGeo::Cartesian.factory
pt1 = factory.point(0, 0)
pt2 = factory.point(2, 0)
pt3 = factory.point(2, 2)
pt4 = factory.point(0, 2)
outerring = factory.linear_ring([pt1, pt2, pt3, pt4, pt1])
square = factory.polygon(outerring)
square.freeze
square.contains?(factory.point(0, 0))
```

### Expected behavior
It should return false.

### Actual behavior
It raise a FrozenError.
```
4: from (irb):10
        3: from /Users/quentinwentzler/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/bundler/gems/rgeo-dec5b55ddb32/lib/rgeo/impl_helper/validity_check.rb:78:in `block (3 levels) in override'
        2: from /Users/quentinwentzler/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/bundler/gems/rgeo-dec5b55ddb32/lib/rgeo/impl_helper/validity_check.rb:103:in `check_validity!'
        1: from /Users/quentinwentzler/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/bundler/gems/rgeo-dec5b55ddb32/lib/rgeo/impl_helper/validity_check.rb:135:in `invalid_reason_memo'
FrozenError (can't modify frozen RGeo::Geos::CAPIPolygonImpl: #<RGeo::Geos::CAPIPolygonImpl:0x3174 "POLYGON ((0.0 0.0, 2.0 0.0, 2.0 2.0, 0.0 2.0, 0.0 0.0))">)
```

### System configuration

**Ruby version**: 3.1.2

**OS**: macOS Monterey 12.3.1

**Comment by keithdoggett** [comment]
@Quiwin thanks for the report and testing out v3! This is indeed a regression, and I can start looking into some fixes soon.

**Comment by keithdoggett** [comment]
Another option we discussed is to check if the object is frozen in `invalid_reason_memo` and run an un-cached check instead. This would cause more compute time whenever a validity check is needed, but would avoid issues with frozen objects. You could also run `valid?` or `check_validity!` before freezing to memoize the result.

Something like this:

```ruby
      def invalid_reason_memo
        # `defined?` is a bit faster than `instance_variable_defined?`.
        return @invalid_reason_memo if defined?(@invalid_reason_memo)
        if frozen?
          puts "notice about perf" unless ENV.key?("SUPPRESS_RGEO_PERF_WARNING")
          return invalid_reason
        end

        @invalid_reason_memo = invalid_reason
      end
```
